export const people = [
    {
        id: 1,
        gender: 'men',
        img: 75,
        name: 'Armie Hammer',
        email: 'armie.hammer@gmail.com',
        position: 'Receptionist',
    },
    {
        id: 2,
        gender: 'women',
        img: 64,
        name: 'Gina Ginnish',
        email: "gina.ginnish@gmail.com",
        position: "Delivery Driver",
    },
    {
        id: 3,
        gender: 'women',
        img: 9,
        name: "Samantha Lowe",
        email: "samantha.lowe@gmail.com",
        position: "Graphic Designer",
    },
    {
        id: 4,
        gender: 'men',
        img: 66,
        name: 'Duane Miles',
        email: 'duane.miles@gmail.com',
        position: 'Manager',
    },
    {
        id: 5,
        gender: 'women',
        img: 8,
        name: 'Eve Leroy',
        email: 'eve.leroy@gmail.com',
        position: 'Project Manager',
    },
    {
        id: 6,
        gender: 'men',
        img: 44,
        name: 'Jorge Callalle',
        email: 'jorge.callalle@gmail.com',
        position: 'Customer Service',
    },
    {
        id: 7,
        gender: 'men',
        img: 52,
        name: 'Sean DJ Doran',
        email: 'sean.dj.doran@gmail.com',
        position: 'Senior Developer',
    },
    {
        id: 8,
        gender: 'women',
        img: 28,
        name: 'Susan Lyall',
        email: 'susan.lyall@gmail.com',
        position: 'Data Entry',
    },
    {
        id: 9,
        gender: 'women',
        img: 55,
        name: 'Preeti Toivonen',
        email: 'preeti.toivonen@gmail.com',
        position: 'Medical Assistant',
    },
    {
        id: 10,
        gender: 'women',
        img: 21,
        name: 'Davina Billings',
        email: 'davina.billings@gmail.com',
        position: 'Accountant',
    }
]